### ISSUE TITLE
'https://github.com/s-weissbach/vine-seg_segmentation.git/' not found

### ISSUE THREAD

**Issue by Tepps-ps** [NiRuff/ViNe-Seg#2]
I want to train a model with my data, but I can't find the provided git page.

**Comment by NiRuff** [comment]
Hey,

thanks for the note. we saw that our collaborator s-weissbach put the git repo private so far, but we'll make it public asap. Gonna write you again as soon as it should work out! :)

**Comment by NiRuff** [comment]
it is public now, so the URL should work now!
